-- ShopIQ operational schema for Supabase (PostgreSQL).
-- Source of truth: DB_SCHEMA.md at repo root.
-- Run once on an empty database before loading INSERT chunks from scripts/prepare_supabase_inserts.py

-- -----------------------------------------------------------------------------
-- 1. customers
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
  customer_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name        TEXT NOT NULL,
  email            TEXT NOT NULL UNIQUE,
  gender           TEXT NOT NULL,
  birthdate        TEXT NOT NULL,
  created_at       TEXT NOT NULL,
  city             TEXT,
  state            TEXT,
  zip_code         TEXT,
  customer_segment TEXT,
  loyalty_tier     TEXT,
  is_active        INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT customers_is_active_check CHECK (is_active IN (0, 1))
);

-- -----------------------------------------------------------------------------
-- 2. products
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
  product_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku          TEXT NOT NULL UNIQUE,
  product_name TEXT NOT NULL,
  category     TEXT NOT NULL,
  price        DOUBLE PRECISION NOT NULL,
  cost         DOUBLE PRECISION NOT NULL,
  is_active    INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT products_is_active_check CHECK (is_active IN (0, 1))
);

-- -----------------------------------------------------------------------------
-- 3. orders
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
  order_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id    INTEGER NOT NULL REFERENCES customers (customer_id) ON DELETE RESTRICT,
  order_datetime TEXT NOT NULL,
  billing_zip    TEXT,
  shipping_zip   TEXT,
  shipping_state TEXT,
  payment_method TEXT NOT NULL,
  device_type    TEXT NOT NULL,
  ip_country     TEXT NOT NULL,
  promo_used     INTEGER NOT NULL DEFAULT 0,
  promo_code     TEXT,
  order_subtotal DOUBLE PRECISION NOT NULL,
  shipping_fee   DOUBLE PRECISION NOT NULL,
  tax_amount     DOUBLE PRECISION NOT NULL,
  order_total    DOUBLE PRECISION NOT NULL,
  risk_score     DOUBLE PRECISION NOT NULL,
  is_fraud       INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT orders_promo_used_check CHECK (promo_used IN (0, 1)),
  CONSTRAINT orders_is_fraud_check CHECK (is_fraud IN (0, 1))
);

CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders (customer_id);

-- -----------------------------------------------------------------------------
-- 4. order_items
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_items (
  order_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id      INTEGER NOT NULL REFERENCES orders (order_id) ON DELETE RESTRICT,
  product_id    INTEGER NOT NULL REFERENCES products (product_id) ON DELETE RESTRICT,
  quantity      INTEGER NOT NULL,
  unit_price    DOUBLE PRECISION NOT NULL,
  line_total    DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items (product_id);

-- -----------------------------------------------------------------------------
-- 5. shipments (warehouse / ML target)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shipments (
  shipment_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id         INTEGER NOT NULL UNIQUE REFERENCES orders (order_id) ON DELETE RESTRICT,
  ship_datetime    TEXT NOT NULL,
  carrier          TEXT NOT NULL,
  shipping_method  TEXT NOT NULL,
  distance_band    TEXT NOT NULL,
  promised_days    INTEGER NOT NULL,
  actual_days      INTEGER NOT NULL,
  late_delivery    INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT shipments_late_delivery_check CHECK (late_delivery IN (0, 1))
);

-- Optional: uncomment when you add ML probability scores (see DB_SCHEMA.md).
-- ALTER TABLE shipments ADD COLUMN IF NOT EXISTS late_delivery_probability DOUBLE PRECISION;

-- -----------------------------------------------------------------------------
-- 6. product_reviews
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product_reviews (
  review_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     INTEGER NOT NULL REFERENCES customers (customer_id) ON DELETE RESTRICT,
  product_id      INTEGER NOT NULL REFERENCES products (product_id) ON DELETE RESTRICT,
  rating          INTEGER NOT NULL,
  review_datetime TEXT NOT NULL,
  review_text     TEXT,
  CONSTRAINT product_reviews_rating_check CHECK (rating >= 1 AND rating <= 5)
);

CREATE INDEX IF NOT EXISTS idx_product_reviews_customer_id ON product_reviews (customer_id);
CREATE INDEX IF NOT EXISTS idx_product_reviews_product_id ON product_reviews (product_id);

-- -----------------------------------------------------------------------------
-- 7. payment_predictions (ML fraud scoring + admin verification)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payment_predictions (
  prediction_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id          INTEGER NOT NULL REFERENCES orders (order_id) ON DELETE RESTRICT,
  model_version     TEXT NOT NULL,
  scored_at_utc     TEXT NOT NULL,
  proba_fraud       DOUBLE PRECISION NOT NULL,
  risk_band_1_100   INTEGER NOT NULL,
  threshold         DOUBLE PRECISION NOT NULL,
  is_fraud_pred     INTEGER NOT NULL DEFAULT 0,
  is_fraud_verified INTEGER,
  verified_by       TEXT,
  verified_at       TEXT,
  metadata_json     TEXT,
  CONSTRAINT pp_is_fraud_pred_check CHECK (is_fraud_pred IN (0, 1)),
  CONSTRAINT pp_is_fraud_verified_check CHECK (is_fraud_verified IS NULL OR is_fraud_verified IN (0, 1)),
  CONSTRAINT pp_order_model_unique UNIQUE (order_id, model_version)
);

CREATE INDEX IF NOT EXISTS idx_pp_order_id ON payment_predictions (order_id);
CREATE INDEX IF NOT EXISTS idx_pp_proba_fraud ON payment_predictions (proba_fraud DESC);

-- -----------------------------------------------------------------------------
-- 8. ml_models (serialized model artifacts for serverless inference)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ml_models (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_version   TEXT NOT NULL UNIQUE,
  created_at      TEXT NOT NULL,
  model_blob      TEXT NOT NULL,
  metadata_json   TEXT
);

-- -----------------------------------------------------------------------------
-- POST-MIGRATION: run after all INSERT chunks have loaded (fixes IDENTITY nextval)
-- -----------------------------------------------------------------------------
-- SELECT setval(pg_get_serial_sequence('customers', 'customer_id'), COALESCE((SELECT MAX(customer_id) FROM customers), 1));
-- SELECT setval(pg_get_serial_sequence('products', 'product_id'), COALESCE((SELECT MAX(product_id) FROM products), 1));
-- SELECT setval(pg_get_serial_sequence('orders', 'order_id'), COALESCE((SELECT MAX(order_id) FROM orders), 1));
-- SELECT setval(pg_get_serial_sequence('order_items', 'order_item_id'), COALESCE((SELECT MAX(order_item_id) FROM order_items), 1));
-- SELECT setval(pg_get_serial_sequence('shipments', 'shipment_id'), COALESCE((SELECT MAX(shipment_id) FROM shipments), 1));
-- SELECT setval(pg_get_serial_sequence('product_reviews', 'review_id'), COALESCE((SELECT MAX(review_id) FROM product_reviews), 1));
